[package]
name = "file_web_devicon_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "stress_test"
harness = false
