[package]
name = "file_web_devicon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file_web_devicon_lib = { path = "../file_web_devicon_lib" }
